40_Webentwicklung/Django_html_templates/news_seite/news/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.meldungen, name='meldungen'),
	url(r'^(?P<meldungs_id>\d+)/$', views.meldungen_detail,
                                name='meldungen_detail'),
]

40_Webentwicklung/Django_html_templates/news_seite/news_seite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^meldungen/', include('news.urls', namespace='news')),
    url(r'^admin/', admin.site.urls),
]

40_Webentwicklung/Django_html_templates/news_seite/news/models.py
from django.db import models

class Meldung(models.Model):
    titel = models.CharField(max_length=100)
    zeitstempel = models.DateTimeField()
    text = models.TextField('Meldungstext')

    def __str__(self):
        return self.titel
		

class Kommentar(models.Model):
    meldung = models.ForeignKey(Meldung)
    autor = models.CharField(max_length=70)
    text = models.TextField('Kommentartext')

    def __str__(self):
        return "{} sagt '{}'".format(self.autor, self.text)

40_Webentwicklung/Django_html_templates/news_seite/news/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext, loader

from .models import Meldung, Kommentar


def meldungen(request):
    return render(request, 'news/meldungen.html',
        context={'meldungen' : Meldung.objects.all()})

	
def meldungen_detail(request, meldungs_id):
    meldung = get_object_or_404(Meldung, id=meldungs_id)
    
    if 'speichere_kommentar' in request.POST:
        name = request.POST.get('besuchername', '')
        text = request.POST.get('kommentartext', '')
        
        if name and text:
            kommentar = meldung.kommentar_set.create(
                autor=name, text=text)
            kommentar.save()
            return HttpResponseRedirect('.')
        
        else:
            return render(request, 'news/meldungen_detail.html',
                context={'meldung' : meldung,
                         'fehler': 'Geben Sie Ihren Namen und ' \
                                   'einen Kommentar an.',
                         'besuchername' : name, 'kommentartext' : text})
    
    return render(request, 'news/meldungen_detail.html',
        context={'meldung' : meldung})

40_Webentwicklung/Django_html_templates/news_seite/news/templates/news/meldungen.html
{% extends 'main/basis.html' %}
{% block titel %}News-&Uuml;bersicht{% endblock %}
{% block inhalt %}
    {% for m in meldungen %}
        <div class="container">
          <div class="titelzeile">
            <div class="titel">{{ m.titel|escape }}</div>
            <div class="zeitstempel">
              {{ m.zeitstempel|date:'Y.m.d' }} um
              {{ m.zeitstempel|time:'H:i' }} Uhr
            </div>
            <div style="clear: both"></div>
          </div>
          <div class="text">
            {{ m.text|escape|linebreaksbr }}
            <div class="link_unten">
              <a href="{% url 'news:meldungen_detail' m.id %}">Details</a>
            </div>
          </div>
        </div>
    {% endfor %}
{% endblock %}

40_Webentwicklung/Django_html_templates/news_seite/news/templates/news/meldungen_detail.html
{% extends 'main/basis.html' %}
{% block titel %}
  News-Details f&uuml;r Eintrag {{ meldung.id }}
{% endblock %}
{% block inhalt %}
  <div class="container">
    <div class="titelzeile">
      <div class="titel">{{ meldung.titel|escape }}</div>
      <div class="zeitstempel">{{ meldung.zeitstempel }}</div>
      <div style="clear: both"></div>
    </div>
    <div class="text">
      {{ meldung.text|escape|linebreaksbr }}
    </div>
  </div>
  <div class="container">
    <div class="titelzeile">Kommentare</div>
    {% if meldung.kommentar_set.count %}
      <table>
      {% for k in meldung.kommentar_set.all %}
        <tr class="kommentarzeile">
          <td class="spaltenbezeichner">{{ k.autor }}:</td>
          <td>{{ k.text|escape|linebreaksbr }}</td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
      Keine Kommentare
    {% endif %}
  </div>
   
  <div class="container">
  <div class="titelzeile">Neuer Kommentar</div>
  <span class="fehler">{{ fehler }}</span>
  <form method="post" action="">
    {% csrf_token %}
    <input type="hidden" name="speichere_kommentar" value="1"/>
    <table>
      <tr class="kommentarzeile">
        <td class="spaltenbezeichner">Ihr Name:</td>
        <td><input type="text" name="besuchername" 
                   value="{{ besuchername }}"/></td>
        </tr>
        <tr class="kommentarzeile">
          <td class="spaltenbezeichner">Kommentar:</td>
          <td>
            <textarea name="kommentartext">{{ kommentartext }}</textarea>
          </td>
        </tr>
      </table>
      <input type="submit" value="Abschicken" />
  </form>
  </div>

   <div class="link_unten">
    <a href="{% url 'news:meldungen' %}">Zur&uuml;ck</a>
   </div>
{% endblock %}

40_Webentwicklung/Django_html_templates/news_seite/news_seite/templates/main/basis.html
<!DOCTYPE html>
<html>
<head>
  <title>Unsere Django-Seite</title>
  <style type="text/css">
    #inhalt {
        border: 2px dotted #94A8BB;
        background-color: #ECFFFF;
        margin: 4%;
        padding: 5px;
    }

    .container {
        border: 1px solid #98BDD8;
        margin-bottom: 10px;
    }
    .titelzeile {
        background-color: #A8D1EF;
        font-weight:bold;
        padding: 1px;
    }
    .titel { float: left; }
    .zeitstempel { float: right }
    .text { padding: 3px; }
    .link_unten {
        margin-top: 3px;
        font-size: 8pt;
    }

    .kommentarzeile { border: 1px solid #A8D1EF; }

    .spaltenbezeichner {
        width: 100px;
        background-color: #B6DEEF;
        font-weight: bold;
        font-size: 10pt;
        text-align: right;
        vertical-align: top;
    }

    .kommentarzeile { border-bottom: 1px solid #A8D1EF; }

    .fehler { color: red }
  </style>
</head>
<body>
  <div id="inhalt">
    <h2>{% block titel %}Django Beispielseite{% endblock %}</h2>
    {% block inhalt %}
    {% endblock %}
  </div>
</body>
</html>